// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyDLypdLCgtw8puVO6p3GdmN8CHINn1Qo',
    appId: '1:131513901586:android:586e3c013b4206bdbeeecb',
    messagingSenderId: '131513901586',
    projectId: 'instagram-clone-riverpod-6607f',
    storageBucket: 'instagram-clone-riverpod-6607f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBp7BtexLIOPXGsUd4G3P1ZRAFiDcHoudw',
    appId: '1:131513901586:ios:6d8edc5fe44d45f7beeecb',
    messagingSenderId: '131513901586',
    projectId: 'instagram-clone-riverpod-6607f',
    storageBucket: 'instagram-clone-riverpod-6607f.appspot.com',
    iosClientId: '131513901586-gmp7fg80br8di3kd5adnntcgaceqcd8d.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramCloneWithRiverpod',
  );
}
